#!/bin/sh

# Set these paths appropriately

BIN="/home/gabrami/Downloads/TreeTagger/bin"
CMD="/home/gabrami/Downloads/TreeTagger/cmd"
LIB="/home/gabrami/Downloads/TreeTagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/persian-coarse.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
