#!/bin/sh

# Set these paths appropriately

BIN="/home/gabrami/Downloads/TreeTagger/bin"
CMD="/home/gabrami/Downloads/TreeTagger/cmd"
LIB="/home/gabrami/Downloads/TreeTagger/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovenian.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
