#!/bin/sh

# Set these paths appropriately

BIN="/home/gabrami/Downloads/TreeTagger/bin"
CMD="/home/gabrami/Downloads/TreeTagger/cmd"
LIB="/home/gabrami/Downloads/TreeTagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/finnish-abbreviations
PARFILE=${LIB}/finnish.par

$TOKENIZER -a $ABBR_LIST $* |
# tagging
$TAGGER $OPTIONS $PARFILE

