#!/bin/sh

# Set these paths appropriately

BIN="/home/gabrami/Downloads/TreeTagger/bin"
CMD="/home/gabrami/Downloads/TreeTagger/cmd"
LIB="/home/gabrami/Downloads/TreeTagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/lithuanian-abbreviations
PARFILE=${LIB}/lithuanian.par
MWLFILE=${LIB}/lithuanian-mwls

$TOKENIZER -a $ABBR_LIST $* |
# recognition of MWLs
$MWL -f $MWLFILE |
# tagging
$TAGGER $OPTIONS $PARFILE
